language: node_js
node_js:
- '10'
- '8'
- '6'
before_install:
- export GREENKEEPER=$([[ $(node -v) == v10.* ]]; echo $?)
- if [[ ${GREENKEEPER} -eq 0 ]]; then npm install -g greenkeeper-lockfile; fi
install:
- npm install
before_script:
- if [[ ${GREENKEEPER} -eq 0 ]]; then greenkeeper-lockfile-update; fi
script:
- npm run test
- npm run lint
after_success:
- if [[ ${GREENKEEPER} -eq 0 ]]; then greenkeeper-lockfile-upload; fi
- npm install -g codecov
- tap --coverage-report=text-lcov > coverage.lcov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: JFS1ZwGCl90rWs/kLNlpH0AoN0mSQIR6fejf0sbVkQb+4Ql0YX0gGtBQR5uvXaJMEHQshmXqkW9emki9zrsitL7S/zvQJq7htAKLNQ926g7U25QAESLuF+CJtv0hgZzxtgSFN2+y+Kdtuk0lrv+lTqBg9DwYaoct1TRa+vHG6VsrPsoXKaxHP7g/1nkDXhgq6jqrBnJcASsq11AwXRaPj9b34Y+f/dhdur1wyLn/lU0dbY/sDxYHbgX6WkteMUA3Z9Hv3iBXZgpUBzKblCmlUNBi5qWjG+gfxB0o+glRGm47/Wj2hunqy86Hqn8M0pcLv8OPI4j0CmRtPj8NxOJUnW2vEoXSWwAhx5S7UTyFWI7v6z2zbI/vAaYu9CNjeaKJcvsnPS4H6SJq9oQN6K6hGKg8vJySWXiT0X/sm3sRKoQdtET853H2Q3PQWbfkkb5bOVnkDKCjwblARaIqfSQyLgSeZFQLnsx20IlsKdmQVTma/OYv/YbuWlYAPjdTe/qjSNVxtnX6bGWnMm+reNYZVuKsCoBphcTR0S55vCvKiOuYlni/fNC2kmj663ggK84OkMvV66cjLFHYqbdAnyHvL+TkQoMOZ9Ydb75I4+yGzKM8RBAalOZna3eBDU2RY5JoatXVjUfrtMWAEHM6Nybmwbmg5ho1oFpit4jndcbD1GE=
  on:
    tags: true
    repo: kei-ito/hexo-deployer-aws-s3
