language: node_js
node_js:
- '10'
- '8'
- '6'
before_install:
- export GREENKEEPER=$([[ $(node -v) == v10.* ]]; echo $?)
- if [[ ${GREENKEEPER} -eq 0 ]]; then npm install -g greenkeeper-lockfile; fi
install:
- npm install
before_script:
- if [[ ${GREENKEEPER} -eq 0 ]]; then greenkeeper-lockfile-update; fi
script:
- npm run test
- npm run lint
after_success:
- if [[ ${GREENKEEPER} -eq 0 ]]; then greenkeeper-lockfile-upload; fi
- npm install -g codecov
- tap --coverage-report=text-lcov > coverage.lcov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: hcZpEyGbqMVnt0D8JuKX+j9RPk3uZUU+jJ0mF45Q0ET0Xj/90XvL++8M4yQFqmOGG4xdoyJjCZ5xrhjd3C1iibyCB5m7vvOHBMZlZxOK0SOGaUnxq6oOI20nu6HpPWq03IssaNk0qpM37xw9MDdaUEOgC80x1MFXJyEMccN/HTjZv7Cjd5s2XrFwuRDnw/Qo8WUuVJV10/eg+ldjlqJjC+AQZn738uy+/QHP5SHnkl3e4Mq9Y11y7EXQnUsC5D1R6bfbKZbhQFu6IXTPY57f8zklbcqbBJKTCER64WwJc1bPKF40aOYXU7gtRbFu7R8WD/lwBA0gOIQPCHYA3kZ3T3NVyvGKS6kIjrZ+QHHwvnJ1WKLx4Lr75LmBRpkC0vCrtYAeiQCSBLpSE065UYKO8jWT8gzVR3zRZUHnTzHvDmpBIBvmatWyOO9DKxadzKJ0hJRI8qcwvrme7Q5FImgetj7PEup/jrE9130QMVKA4SAbWXm8hk31VyGlqf3e2DQYIWBc0uYdTzZLZJ0L3N5RB7vezvwwoE+Wwuy6ezGAZ5udOEZFlnW178dkMsBTn4Cm4IrQh5gwv3ndwlUlKzA02CRSlJfJTBLTkiMqZ0Om/Rz/WR0uTJ/2swUF9eIqfIDhIgGejV93sVvmO2h8nWcM7I3gu7w2ihk0v02wfAxowuQ=
  on:
    tags: true
    repo: kei-ito/hexo-deployer-aws-s3
    branch: master
env:
  global:
    secure: WI6etHhVK4986hnzpIEqSsQqJaPvSoOV5c1fSTjAMtkus8h+uJhpx5Wpau4vyCHIRuFGYfLXzUuIxJ6vml5OKbSl8DmQyCHx8PceZckUTtiL8BFeNf9RdHEfPcrFCkz1WQf4PSXTa1DRn2Nu8A1Wld8aXQXObPinlzw2Za0hIORrVlf2LRFAX6NCEUsTrE/lji1dmngxK1Rrt7jIsdp1QDjn9zIOLWsIkbkZNMEIXmRlSHb9j8nhyjZsvrXjWUl0lGo8G3WCAvNDMiJ0H5RabdLU8loZ/37bfgWMDpiTPJgJ6SfbvIUIzK0LDBOfxXI/yUEq5f2dnKKnTi/DZ0gOJT2L1J0XqGiK08ec+UbgpiuY0DN9F5yn9LiEPx37MzKk5Ct7c/THqkI7DVPtBXz++1TtXkVGb6dcsXpkBHFJwobbRDQznefqX5mSZkZuPzFN3YUWQiHzSt1NHgOun5zXuTVsElk97rs3obahePjbNkYw7drCX4jlQ3bMNQzlomPq+8Oxhvkj+jqfkB0LSnyscrnGgJcHx1lafwg3yHwlXYbsGENloknImwNpcNUKo+eQSkwewuIc0uMmuI5e144NvJoVYlqjLSvM7gA2HoTze8lfjdxfBh3zzy8EI4R1v22uLfjcK0m+b0lZJSza2e8kBJG3/V+18gM3uA7e6anKGwQ=
