language: node_js
node_js:
- '7'
- '6'
- '5'
- '4'
script: npm run test_coverage
after_success:
- npm install codacy-coverage
- cat ./coverage/lcov.info | ./node_modules/codacy-coverage/bin/codacy-coverage.js
  --debug
notifications:
  slack:
    secure: kx/jfvjX4yBaUF5v1x3sl8Nt+ncOtfWwg0rd2OxICz4LIbZ1MGU5aaVrDCpKNWeBoNkS9bwUR79azQuSsrG8nJ9EbM4nxfK2kbUpU77OXvyo/usJokCtpEY7t/oCyTfl5YfJC3kNnPAjv6gVzKkLGHxS/eo6hQ6mHyArCFzjXgrBKFyM0RYo+7lWcDtKuxWYcIXRLmvzBoKRzsps2MNe1msU3bX7FgWPIXtfeWQDCTCknlKQC0zfNmFU0XpnzT0Fb+cE8npjtyQ46giCjOZ4NsPpTwamp2FKI3c63r/fSViIC1+CpDK03XtIMYx8Gjwq9uNXBS8IayQO94NdaB9PVu87MBrRAWkq9kwHfrdF90DCMwOVZzxuq2vgd/Ouzi1LcH1FaZXTKn4RcKAMHnWqOvG/XgvMz+mDqF1DQb6B+S1rZm7QpRbgf1aJcxdlbjHOFG/JRPODxq3X7NWrN4djrdkiuvBf05g23yPVxwBbdxF/hbnRoiYalurXA0w37k94FyYoZvuvV5gTg9ejtTr+biyKSQ8J+tCxhSOJP3xinwOWUxkxblrJjMUDPnUXcgvl+E65LxN7QXc5CZYG6WqhudfRwno6mPrlD+9yGnQJvy17BqnSBmGA6gH88z3xlM0hhA4dI6zgdGmfCt/B3SGfw6t8cIP+WP2coXTpsroc92A=
env:
  global:
    secure: mxb+f5vv7pmg/EWk7zWqyJEyFklf3tsRh7i0gCF/WfyVW4Kvr1346mkx1c0IDj1ZU7zz5FkZN8yoeIFGO7ZyIrcnHDy3PBHnD2W453OaPFzAVDQ13ozBmHy3zKCz42GGSoKwSi7wBBmWUDXTJOGuQVgLtCVOqnF6r3025WCHuooQP29wEd2KPmbKeYyMkRyYSDmGlcZuaLKZPBo+5IQk0HUfX5PJx2rOu+SfhXhrSkZP90Fl1qlTymOhEPtxoitsSPrsFu+gujhNtWF1n95jAIHb0bDbJ6+F1QO+XqmPIockdxJ3Q7IJ9jnxOed6quMbjGDwLsD/q50DXhaEfZqcRRZVYWNSgP6O+Y3P/NWZYeR5b+kEcW3KBwWy6TwVQhRP9NAMvvlF0bjDyLea+6bZx2KN/l/iyVhjDvQhXkKJBdQS9zcN3X0MDp+FZq34/DkvicDUbPe5GBgHY34vcgq0TcjPhJ6ot9e/snlgPUoDXFlrBkDO50CAieAq7OyTEFO+L0KjhQXjmdT5+b2x0cqBDo9IYlKgPLRTW0a6IuZIohq2qH0gqI5B0iHnupKrCCuMoQXPZLqrL0BnjXNeOIkxmJ7l4CvVvXaqwLuaCUXPnmhZgTvcF26axpfpPguwIPNDG5/CAfKYxqmbEUP5XBQ5GyeuasUzJBcrstHT+5fyzuY=
